### ISSUE TITLE
[Self-Managed]: No logs available under agent Logs tab for installed fleet server agent

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/fleet-server#1285] opened 2022-04-01 06:57 UTC
**Describe the bug**
[Self-Managed] Logs are not displayed for agent installed

**Build Details:**
```
Version: 8.2.0 BC1
Commit:d18a093a2cf03991b93ea3de6a1054d580d3e82f
Build:51685
```

**preconditions**
1. Policy should be exist or created

**Steps to Reproduce**
1. Navigate to fleet tab
2. Install the agent with policy.
3. Navigate to logs tab
3. Observe that Logs are not displayed for agent installed

**Actual Result**
Logs are not displayed for agent installed

**Expected Result**
Logs should be displayed for agent installed

**Screen-Shot**

![image](https://user-images.githubusercontent.com/61860752/161210394-bd53f98a-2451-4b83-a0a2-1b15304b90b7.png)

**Logs**
[logs.zip](https://github.com/elastic/fleet-server/files/8395367/logs.zip)

**Comment by manishgupta-qasource** [comment] 2022-04-01 10:52
Secondary review for this ticket is Done

**Comment by ph** [comment] 2022-04-01 12:18
@deepikakeshav-qasource can you send me a diagnostics per email? fyi @jlind23 can someone look into this one.

**Comment by jlind23** [comment] 2022-04-01 12:22
What are the agent logs? Is the agent started on the host?

**Comment by jlind23** [comment] 2022-04-01 12:28
@lykkin could you answer here?
The error appears to be 

> {"log.level":"info","@timestamp":"2022-04-01T05:51:40.802Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-04-01T01:51:40-04:00 - message: Application: fleet-server--8.2.0[]: State changed to DEGRADED: Running on policy with Fleet Server integration: 5d2cbfb0-b170-11ec-aac8-5db5d996a3c5; missing config fleet.agent.id (expected during bootstrap process) - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}

It seems to be linked to your change on the default policy.

**Comment by ph** [comment] 2022-04-01 12:40
I have a few questions:
 
The agent logs in the zip are from the Elastic Agent running Fleet server?

Did you run into any issues when installing/enrolling that agent in fleet-server?
The warning message `fleet.agent.id` should have ben generated outside of fleet-server in the agent, and I wonder if there is something that was raised during the `enrollment` process? I would have expected the enrollment fails on hard errors but maybe some warning was emitted.

**Comment by amolnater-qasource** [comment] 2022-04-06 09:11
Hi @ph 
>The agent logs in the zip are from the Elastic Agent running Fleet server?

The attached agent logs we shared earlier in the zip are from the Fleet-Server agent that is installed using user created Fleet Server policy having System and Fleet Server integration.
We attempted this on 8.2 BC-1 Kibana self-managed environment.

>Did you run into any issues when installing/enrolling that agent in fleet-server?

We haven't observed any issues in installation of this Fleet Server at console.
To avoid any confusions we have updated the defect summary.
Thanks

**Comment by jlind23** [comment] 2022-04-06 12:08
@amolnater-qasource it seems to be the exact same behaviour as in https://github.com/elastic/elastic-agent/issues/281
If you agree, can we keep only one?

cc @AndersonQ

**Comment by amolnater-qasource** [comment] 2022-04-06 12:33
@jlind23 We have reported this issue because:
- Firstly we have observed this on **self-managed environment**.
-  The **Fleet-Server agent** was not generating any logs on **Fleet UI** under Agent>Logs tab.

The other log issues we have reported were for Elastic-Agent installed on Kibana cloud environments.
Thanks!

**Comment by amolnater-qasource** [comment] 2022-04-07 12:08
Hi @jlind23 
We have revalidated this issue on 8.2 BC-2 Kibana self-managed environment and found it **not reproducible** now.
- Logs are available under agent logs tab for Fleet Server installed on a self-managed environment.

**Build details:**
BUILD: 51772
COMMIT: 3535a206838845689639344afaf64a58c663b3c1
Artifact Link: https://staging.elastic.co/8.2.0-1bde7c3b/downloads/beats/elastic-agent/elastic-agent-8.2.0-windows-x86_64.zip

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/162194433-e70ae852-b37b-4863-80e2-b860b99420bc.JPG)

Hence we are **closing** this issue.
Thanks

**Closed by amolnater-qasource** 2022-04-07 12:08 UTC
Labels: bug, impact:high, Team:Elastic-Agent-Control-Plane

**Comment by amolnater-qasource** [comment] 2022-05-11 11:15
### `Bug Conversion`

-  Testcase already exists for this scenario under Fleet test suite at link:
   - [C15282](https://elastic.testrail.io/index.php?/cases/view/15282)

Thanks!
