### ISSUE TITLE
Fleet-server docs overview

### ISSUE THREAD

**Issue by ruflin** [elastic/fleet-server#184] opened 2021-03-30 06:33 UTC
This issue is to keep a list of all the things that should be documented for fleet-server.

* [ ] What is fleet-server. Describe architecture on a high level
* [ ] How is fleet-server run / setup
  * [ ] Prerequisites, eg. 7.13+, ECE 2.10+ 
  * [ ] What params exist
  * [ ] What environment variables exist
  * [ ] What needs to be done in Fleet?
  * [ ] How to enroll an Elastic Agent into fleet-server
* [ ] Existing config options
* [ ] Fleet-server in docker
  * [ ] How is it different? Non upgradable, different paths https://github.com/elastic/beats/pull/24817
  * [ ] What environment variables exist
  * [ ] Example setup for docker-compose
* [ ] Monitoring of fleet-server
* [ ] Setup in Kubernetes
* [ ] Compatibility: Elasticsearch >= Fleet Server >= Elastic Agent. Bugfix releases might differ. Kibana is assumed to be on the same minor as Elasticsearch.

**Comment by mostlyjason** [comment] 2021-04-15 19:08
This issue is a duplicate of https://github.com/elastic/observability-docs/issues/449 so I merged the items from this list into the other one

**Closed by mostlyjason** 2021-04-15 19:08 UTC
Labels: Team:Agent, docs
