### ISSUE TITLE
[Fleet] Re configuring fleet server from an agent policy do nothing 

### ISSUE THREAD

**Issue by nchaulet** [elastic/fleet-server#284] opened 2021-04-27 14:14 UTC
##  Description 

I tried to change the port of Fleet server from the edit integration UI and looks like it's not used by Fleet sever

<img width="901" alt="Screen Shot 2021-04-27 at 10 12 17 AM" src="https://user-images.githubusercontent.com/1336873/116256348-1ad7df80-a741-11eb-8560-cd9b189edf54.png">

After that the agent log says it got the policy but there is no fleet server running at `:8221` still one running on `:8220`

Fleet server logs
<img width="1307" alt="Screen Shot 2021-04-27 at 10 13 57 AM" src="https://user-images.githubusercontent.com/1336873/116256569-4e1a6e80-a741-11eb-939b-925febe1b24e.png">

**Comment by blakerouse** [comment] 2021-04-27 14:34
Seems like a duplicate of #172. I think this is the same issue, just a different field.

**Closed** 2021-04-27 14:40 UTC
Labels: bug
