### ISSUE TITLE
[Fleet]: Fleet Server stuck in updating state after installation.

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/fleet-server#1934] opened 2022-09-29 11:34 UTC
Kibana version: 8.4.3 BC2 Kibana Cloud environment

Host OS and Browser version: Windows

**Build details:**
VERSION: 8.4.3 BC2
Build: 55572
Commit: 1ceb607762eaafa726c61d6eee5b95359142d4c4

**Preconditions:**
- 8.4.3 BC2 Kibana Cloud environment should be available.

**Steps to reproduce:**
1. On fresh Kibana setup navigate to Fleet tab.
2. Click 'Add Fleet Server'.
3.  Generate Fleet-server policy say `https//10.10.10.10:8220`
4. Copy the command in the cli.
5. Fleet-server is installed.
6. Observe Fleet Server is stuck on updating state.

**Expected Result:**
Fleet Server should not stuck in updating state after installation and should be healthy.

**Screenshot:**
![image](https://user-images.githubusercontent.com/102019374/193018473-5d359fc3-2407-41fa-965f-373fcaf3f692.png)

**Elastic-agent logs:**
[elastic-agent-diagnostics-2022-09-29T11-31-36Z-00.zip](https://github.com/elastic/fleet-server/files/9674190/elastic-agent-diagnostics-2022-09-29T11-31-36Z-00.zip)

**Comment by dikshachauhan-qasource** [comment] 2022-09-29 11:39
Secondary Review is done.

**Comment by cmacknz** [comment] 2022-09-29 19:02
Probably a duplicate of https://github.com/elastic/elastic-agent/issues/760

**Comment by simranvaseer-qasource** [comment] 2022-09-30 05:51
Hi @cmacknz 
I have observed that the attached logs was incorrect. Further, I have attached the correct logs below:

Elastic-agent log:
[elastic-agent-diagnostics-2022-09-30T04-12-58Z-00.zip](https://github.com/elastic/fleet-server/files/9681057/elastic-agent-diagnostics-2022-09-30T04-12-58Z-00.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by joshdover** [comment] 2022-09-30 09:27
I don't think this is a Fleet Server problem, the logs for FS look normal to me. There are a couple other interesting things in the logs.

It looks like the agent is in a bootloop due to this error:

`{"log.level":"error","@timestamp":"2022-09-30T03:55:41.968Z","log.origin":{"file.name":"status/reporter.go","file.line":326},"message":"Elastic Agent status changed to \"error\": \"app filebeat--8.4.3--36643631373035623733363936343635-dfb4be0f: \\\"filebeat_monitoring\\\" failed to prepare monitor for \\\"Filebeat\\\": failed to create a directory \\\"\\\": mkdir : The system cannot find the path specified.\"","ecs.version":"1.6.0"}`

There's 8 elastic-agent log files and all of them have the _exact same_ contents, right down to the timestamps in milliseconds, this seems like a bug of sorts.

The agent policy is empty in the diagnostic, but I think that's due to the agent not checking in with Fleet Server (itself) yet. There's this error generated while capturing the diag itself:

```
Error 1: unable to gather diagnostics data: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open \\\\.\\pipe\\elastic-agent-system: The system cannot find the file specified."
Error 2: unable to gather metrics data: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open \\\\.\\pipe\\elastic-agent-system: The system cannot find the file specified."
Error 3: unable to gather config data: no fleet config retrieved yet
```

**Comment by michalpristas** [comment] 2022-10-03 16:39
This was fixed but fix did not make it to BC2
![image](https://user-images.githubusercontent.com/1522652/193631716-06398e97-9d0b-4a79-88ed-b1ed4c20fecd.png)

Fix PR: https://github.com/elastic/elastic-agent/pull/1371
Issue: https://github.com/elastic/elastic-agent/issues/1361

**Comment by cmacknz** [comment] 2022-10-03 17:34
Closing as fixed by https://github.com/elastic/elastic-agent/pull/1372

**Closed by cmacknz** 2022-10-03 17:34 UTC
Labels: bug, Team:Fleet, blocker, impact:medium

**Comment by simranvaseer-qasource** [comment] 2022-10-05 09:32
Hi Team
We have revalidated this issue on latest 8.4.3 BC3 kibana cloud environment and found it **fixed** now.

- Fleet Server is healthy after installation.

**Build Details:**
Version: 8.4.3 BC3
BUILD: 55572
COMMIT: 1ceb607762eaafa726c61d6eee5b95359142d4c4

**Screenshot:**

![image](https://user-images.githubusercontent.com/102019374/193995636-a04b08c3-37ae-4628-a90f-6ed1152bdf1c.png)
Hence, marking this as QA:Validated.
Thanks
