### ISSUE TITLE
gRPC error when running server on ARM

### ISSUE THREAD

**Issue by mdelapenya** [elastic/fleet-server#297] opened 2021-04-28 15:10 UTC
The following error appears randomly when running tests in ARM workers:

>Error: failed to trigger elastic-agent daemon reload: rpc error: code = Unavailable desc = transport is closing

We have seen this behaviour not in a consistent manner: we bootstrap the server in 4 different/parallel executions (in separate workers), and it seems to fail in a non deterministic way. We have seen failing for 1 of 4 in different executions:

- Bootstrap successful: https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/branches/PR-707/runs/45/nodes/460/steps/1855/log/?start=0 (_Search the `Fleet server was bootstrapped for the agent` string_)
- Bootstrap failed:  https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/e2e-tests/pipelines/e2e-testing-mbp/branches/PR-707/runs/45/nodes/464/steps/1829/log/?start=0 (_Search for the `Error: failed to trigger elastic-agent daemon reload: rpc error: code = Unavailable desc = transport is closing` string_)
 
## System info
- Version: 8.0.0-SNAPSHOT
- Operating System:  linux
- Platform: ARM

## Steps to Reproduce
1. Start the elastic stack, being ES running on `http://elasticsearch:9200`
2. Extract 8.0.0-SNAPSHOT TAR file for the elastic-agent in an ARM machine
3. Execute install command to bootstrap fleet-server:

```shell
$ /elastic-agent/elastic-agent install --force --fleet-server-es http://elasticsearch:9200 --fleet-server-service-token AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2MTk1ODAyNTYzMDk6QkpkMkZrOEFRVnlCWjJZalBtYkFvQQ
```

**Expected result:**
The server is bootstrapped
>[2021-04-28T03:24:10.376Z] The Elastic Agent is currently in BETA and should not be used in production
[2021-04-28T03:24:10.376Z] 
[2021-04-28T03:24:14.399Z] 2021-04-28T03:24:13.744Z	INFO	cmd/enroll_cmd.go:301	Generating self-signed certificate for Fleet Server
[2021-04-28T03:24:16.913Z] 2021-04-28T03:24:16.785Z	INFO	cmd/enroll_cmd.go:589	Waiting for Elastic Agent to start Fleet Server
[2021-04-28T03:24:20.054Z] 2021-04-28T03:24:19.842Z	INFO	cmd/enroll_cmd.go:629	Fleet Server - Starting
[2021-04-28T03:24:22.546Z] 2021-04-28T03:24:21.844Z	INFO	cmd/enroll_cmd.go:603	Fleet Server - Running on default policy with Fleet Server integration; missing config fleet.agent.id (expected during bootstrap process)
[2021-04-28T03:24:24.224Z] Successfully enrolled the Elastic Agent.
[2021-04-28T03:24:24.224Z] Elastic Agent has been successfully installed.
[2021-04-28T03:24:24.224Z] 2021-04-28T03:24:23.589Z	INFO	cmd/enroll_cmd.go:204	Successfully triggered restart on running Elastic Agent.
[2021-04-28T03:24:24.224Z] time="2021-04-28T03:24:23Z" level=debug msg="Docker compose executed." cmd="[exec -T fleet-server-centos timeout 5m /elastic-agent/elastic-agent install --force --fleet-server-es http://elasticsearch:9200 --fleet-server-service-token AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2MTk1ODAyNDgzMzE6bVlCZDNHekpTQ2k2YzdoQzJXYko1QQ]" composeFilePaths="[/var/lib/jenkins/workspace/PR-707-44-d3ee5a8c-777d-4232-a768-23c81be98ecf/.op/compose/profiles/fleet/docker-compose.yml /var/lib/jenkins/workspace/PR-707-44-d3ee5a8c-777d-4232-a768-23c81be98ecf/.op/compose/services/fleet-server-centos/docker-compose.yml]" env="map[fleet_server_centosAgentBinarySrcPath:/tmp/elastic-agent-8.0.0-SNAPSHOT-linux-arm64.tar.gz036562456 fleet_server_centosAgentBinaryTargetPath:/elastic-agent-8.0.0-SNAPSHOT-linux-arm64.tar.gz fleet_server_centosContainerName:fleet_fleet-server-centos_elastic-agent_1 kibanaDockerNamespace:kibana kibanaVersion:8.0.0-SNAPSHOT stackPlatform:linux/arm64 stackVersion:8.0.0-SNAPSHOT]" profile=fleet
[2021-04-28T03:24:24.224Z] time="2021-04-28T03:24:23Z" level=info msg="Hostname retrieved from the Docker client" containerName=fleet_fleet-server-centos_elastic-agent_1 hostname=aa57b34e494d
[2021-04-28T03:24:24.224Z] time="2021-04-28T03:24:23Z" level=info msg="Fleet server was bootstrapped for the agent" fleetServerHostname= image=centos installer=tar

**Current result:**
> [2021-04-28T03:24:18.175Z] The Elastic Agent is currently in BETA and should not be used in production
[2021-04-28T03:24:18.176Z] 
[2021-04-28T03:24:24.503Z] 2021-04-28T03:24:23.586Z	INFO	cmd/enroll_cmd.go:301	Generating self-signed certificate for Fleet Server
[2021-04-28T03:24:24.503Z] {"level":"debug","time":"2021-04-28T03:24:23Z","message":"gathering metrics"}
[2021-04-28T03:24:25.575Z] Error: failed to trigger elastic-agent daemon reload: rpc error: code = Unavailable desc = transport is closing
[2021-04-28T03:24:26.087Z] Error: enroll command failed with exit code: 1
[2021-04-28T03:24:26.087Z] time="2021-04-28T03:24:26Z" level=error msg="Could not execute command in service container" command="[timeout 5m /elastic-agent/elastic-agent install --force --fleet-server-es http://elasticsearch:9200 --fleet-server-service-token AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2MTk1ODAyNTYzMDk6QkpkMkZrOEFRVnlCWjJZalBtYkFvQQ]" error="Could not run compose file: [/var/lib/jenkins/workspace/PR-707-44-e2021006-cc18-4b3c-8836-e09641de620a/.op/compose/profiles/fleet/docker-compose.yml /var/lib/jenkins/workspace/PR-707-44-e2021006-cc18-4b3c-8836-e09641de620a/.op/compose/services/fleet-server-centos/docker-compose.yml] - Local Docker compose exited abnormally whilst running docker-compose: [exec -T fleet-server-centos timeout 5m /elastic-agent/elastic-agent install --force --fleet-server-es http://elasticsearch:9200 --fleet-server-service-token AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2MTk1ODAyNTYzMDk6QkpkMkZrOEFRVnlCWjJZalBtYkFvQQ]. exit status 1" service=fleet-server-centos

**Comment by EricDavisX** [comment] 2021-04-28 15:21
Pushing it to Michal, cause he may be available shorty, please reassign as needed.  I'll add it to the urgent 7.13 list.

**Comment by michalpristas** [comment] 2021-05-06 13:25
this looks to me like a timing issue, trying to reproduce with very low success rate of hitting the issue.
maybe we're hitting some weird condition in between restarts where during initial check agent is running and during restart invocation  it's not. 

i will add a retry with a backoff option to see if we can manage to get rid of the condition

**Comment by EricDavisX** [comment] 2021-05-17 14:26
@mdelapenya do we think the above has corrected the problem we were seeing?

**Comment by mdelapenya** [comment] 2021-05-17 14:33
We are seeing another errors before this, related to the ARM worker itself, not the elastic-agent code. Let me continue debugging the original issue, and I'll close this one once fixed. We can set a low priority label if it helps.

**Comment by michalpristas** [comment] 2021-06-18 09:48
@mdelapenya any progress since your last comment?

**Closed** 2024-05-27 15:00 UTC
Labels: bug, Team:Elastic-Agent, automation, v7.14.0, arm
