### ISSUE TITLE
A new managed fleet server shows up, once logging level is changed of existing one.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/fleet-server#1028] opened 2021-12-24 06:43 UTC
**Kibana version:**  8.0 snapshot Kibana on-prem environment

**Browser version:** Chrome
**Host OS**: **n/a**

**Preconditions:**
1. 8.0 snapshot Kibana on-prem environment should be available.

**Build Details:**
```
BUILD 48841
COMMIT 0668b86594c26a088cd166c70b860eeb4e6938dc

```
2. **Apm and fleet should be enabled while creating deployment.**

**Steps to reproduce:**
- Login to kibana
- Navigate to Fleet tab. 
- Click on Fleet server agent and navigate to logs tab . 
- Change the agent logging level.
- Observe, Existing fleet server went to offline state and new fleet server appears **with same container ID**.

**Expected result:**
- **Either logging level field for fleet server should NOT be editable as user is not allowed to make any changes at managed host.**
- **Also, as logs tab has no data to displayed off. It should not be available for managed host as serves no purpose.**

**Screenshot:** 
![image](https://user-images.githubusercontent.com/72375798/147325705-9f865644-4e6e-4a95-b9e8-03b0bb532c9a.png)

![image](https://user-images.githubusercontent.com/72375798/147325840-c85291bf-7ec5-4a6d-b6bd-aa5443f9d5d0.png)

**Comment by manishgupta-qasource** [comment] 2021-12-24 08:09
Reviewed & mention @jen-huang

**Comment by jen-huang** [comment] 2022-01-04 20:25
@nimarezainia or @mostlyjason, do we expect to be able to change the logging level for the managed Fleet Server host on Cloud?

**Comment by mostlyjason** [comment] 2022-01-10 20:44
@nimarezainia this is more in your ball court since its a fleet server / hosted agent issue. More advanced operators might appreciate more insight for troubleshooting, but I'm not sure if there is sensitive data in debug logs.

**Comment by amolnater-qasource** [comment] 2022-03-09 10:00
Hi @mostlyjason 
We have attempted to change log level for Hosted fleet server on 8.2 Snapshot and found it **reproducible** there.
- On changing log level for hosted fleet server a new Hosted fleet server gets installed with the "info" logging level.

Further this issue is **also reproducible on 8.1** released Kibana cloud environment.

**Screenshots:**
![4](https://user-images.githubusercontent.com/77374876/157413016-f31afeda-5e22-4356-8ebf-8ba080fb97f2.JPG)
![5](https://user-images.githubusercontent.com/77374876/157413023-5badc15d-6c81-42ce-8a40-cb9461b3d352.JPG)

**Build details:**
```
VERSION: 8.2.0 Snapshot
BUILD: 50826
COMMIT: e694507960d61def6ebbde146a6cb296b1a74c96
```
Thanks

**Comment by jlind23** [comment] 2022-11-23 15:50
@amolnater-qasource @dikshachauhan-qasource is this still relevant or can I close it?

**Comment by amolnater-qasource** [comment] 2022-11-24 05:46
Hi @jlind23 

We are currently blocked to retest this issue as per https://github.com/elastic/elastic-agent/issues/1731 issue.

We will be revalidating this issue once 8.6 BC3 is available.

Thanks

**Comment by cmacknz** [comment] 2022-11-29 01:13
BC3 is now available for re-testing

**Comment by amolnater-qasource** [comment] 2022-11-30 04:34
Hi @cmacknz @jlind23 

We have revalidated this issue on latest 8.6 BC3 kibana cloud-production environment and observed that the issue is still reproducible.

**Observations:**
- A new hosted fleet server shows up, on changing log level for the existing fleet server.

**Build details:**
BUILD: 58485
COMMIT: b52b34c2ff5216c395bd49c5fbc97744b646f34d

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/204704329-4579d8ba-5f60-4455-80c0-eae510f875f9.mp4

Please let us know if anything else is required from our end.

Thanks

**Comment by jlind23** [comment] 2022-11-30 06:33
@belimawr I saw you are assigned to this [issue](https://github.com/elastic/elastic-agent/issues/1137), correct me if I am wrong but it seems to be the occurence of this right? Closing this issue as we will follow up in the other one.

**Closed by jlind23** 2022-11-30 06:33 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane

**Comment by belimawr** [comment] 2022-11-30 10:14
> @belimawr I saw you are assigned to this [issue](https://github.com/elastic/elastic-agent/issues/1137), correct me if I am wrong but it seems to be the occurence of this right? Closing this issue as we will follow up in the other one.

I haven't looked into the issue yet, but it seems to be the same bug/issue.
