### ISSUE TITLE
Issues with Logstash output on cloud.

### ISSUE THREAD

**Issue by ph** [elastic/fleet-server#1256] opened 2022-03-23 14:43 UTC
Recent changes to support Logstash (https://github.com/elastic/fleet-server/pull/1188) cause some problems, we have reverted it in https://github.com/elastic/fleet-server/pull/1252
--
Kibana version: 8.2.0-SNAPSHOT

Steps to reproduce:

Create 8.2.0-SNAPSHOT deployment on cloud staging
Ingest some data to APM Server, for example either use the apm-integration-testing repository, or post an [example payload](https://www.elastic.co/guide/en/apm/guide/master/api-event-example.html) via curl curl -i -k -H "Content-type: application/x-ndjson" -H "Authorization: Bearer ${ELASTIC_APM_SECRET_TOKEN}" --data-binary @events.ndjson ${ELASTIC_APM_SERVER_URL}/intake/v2/events
Navigate to https://admin.staging.foundit.no/, find your deployment and open the Agent Logs tab and observe errors like
Failed to connect to backoff(elasticsearch(http://localhost:9200)): Get "http://localhost:9200": dial tcp [::1]:9200: connect: cannot assign requested address
It looks like the APM Server, which is receiving the ES config from Fleet and Elastic Agent is trying to connect to ES via http://localhost:9200.

It also seems that the output handling in Fleet changed in 8.2. Navigating to Fleet/Elastic Agent on Cloud policy/Settings let users choose a different Elasticsearch output. Aside from not being convinced that this should be allowed on cloud, chosing a different output than configured breaks the Integrations Server setup, and a complete restart is required.

**Comment by lykkin** [comment] 2022-03-24 06:29
after doing more digging, i think the root cause is an inaccuracy in the way the outputs are named. here's a snippet of a config request from the agent before it gets sent down:
```
{AST:{agent:{monitoring:{enabled:true},{logs:true},{metrics:true},{namespace:default},{use_output:default}}},{monitoring_checksum:101498a889672bae78fc69dac1429a0f},{output:{elasticsearch:{api_key:{Id:Bul_un8BfGcRBobzJMTK},{Key:kfOqBxEQQcCR3Fvd5IYjTw}},{hosts:[http://rg.twitter.com:9222]},{type:elasticsearch}}},{programs:[filebeat,fleet-server,metricbeat]}}
```

Note that the `use_output` value is `default`, but the output name is `elasticsearch`.

**Comment by nchaulet** [comment] 2022-03-24 13:22
> after doing more digging, i think the root cause is an inaccuracy in the way the outputs are named. here's a snippet of a config request from the agent before it gets sent down:

@lykkin it is a bug in the policy we send to the agent? or the default appear after some transformation on your side?

**Comment by lykkin** [comment] 2022-03-24 15:04
@nchaulet reverting the fleet server changes i made fixed the issue, so it's most likely an issue there. i'll keep this issue updated as i learn more

**Comment by jlind23** [comment] 2022-03-24 18:33
You mean with the policy reported by fleet that was containing multiple outputs including a logstash one right?

**Comment by lykkin** [comment] 2022-03-24 20:05
I've narrowed this down to the ssl block in the output: when removing the ssl block the address the beats get are correct. I suspect the dummy values I'm using for the ssl values are causing some issues while resolving the connection, then it defaults back to `localhost:9200`

@nchaulet it looks like when updating a logstash output to an elasticsearch output the ssl block sticks around, which causes an issue.  I'm going to check if this issue is present on fresh policies, which would explain the symptoms that others are seeing.

>You mean with the policy reported by fleet that was containing multiple outputs including a logstash one right?
Just one output. I haven't tried with multiple outputs, just the default settings.

**Comment by nchaulet** [comment] 2022-03-24 20:09
> @nchaulet it looks like when updating a logstash output to an elasticsearch output the ssl block sticks around, which causes an issue. I'm going to check if this issue is present on fresh policies, which would explain the symptoms that others are seeing.

Yes you are correct it seems to have a bug here when we transform a logstash output to an elasticsearch one the ssl props are not remove, I am going to fix that. But for the cloud policy we should not have a logstash output so it seems not related correct?

**Comment by lykkin** [comment] 2022-03-24 20:09
> I'm going to check if this issue is present on fresh policies, which would explain the symptoms that others are seeing.

It looks like policies are generated using a different policy as a template. I created a fresh policy and the output block from the first policy I was working from was copied over, including the ssl block.

**Comment by lykkin** [comment] 2022-03-24 20:10
> > @nchaulet it looks like when updating a logstash output to an elasticsearch output the ssl block sticks around, which causes an issue. I'm going to check if this issue is present on fresh policies, which would explain the symptoms that others are seeing.
> 
> Yes you are correct it seems to have a bug here when we transform a logstash output to an elasticsearch one the ssl props are not remove, I am going to fix that. But for the cloud policy we should not have a logstash output so it seems not related correct?

That sounds right to me, now that I have a better understanding of the issue I'll test it against the cloud instance I was using prior.

**Comment by lykkin** [comment] 2022-03-24 20:52
I found the issue in the cloud case:

this block here: https://github.com/lykkin/fleet-server/blob/logstash-output/internal/pkg/policy/policy_output.go#L82-L84
should have a predicate like
```diff
-			if ok := setMapObj(outputMap, outputAPIKey, p.Name, "api_key"); !ok {
+		        if ok := setMapObj(outputMap, outputAPIKey.Agent(), p.Name, "api_key"); !ok {
				return ErrFailInjectAPIKey
			}
```

The current thing it is throwing on the policy to be shipped down is an object, and it is expecting a string :face_exhaling:

I'll have a PR up for this fix after testing to make sure this solves the problem.

**Closed** 2022-03-28 17:39 UTC
Labels: Team:Elastic-Agent-Control-Plane, v8.2.0
