### ISSUE TITLE
[Self-managed]: Unable to install fleet-server on 8.4.2 

### ISSUE THREAD

**Issue by deepikakeshav-qasource** [elastic/fleet-server#1869] opened 2022-09-15 07:18 UTC
Kibana version: 8.4.2 Kibana self-managed environment

Host OS and Browser version: Windows

**Build details:**
VERSION: 8.4.2 Snapshot self-managed
BUILD: 55523
COMMIT: d34da2c98a97aac80c2b9e8ab197c76cc149574e

**Preconditions:**
- 8.4.2 Kibana self-managed environment should be available.

**Steps to reproduce:**
1. On fresh Kibana setup navigate to Fleet tab.
2. Create Fleet Server Policy.
3. Select 'Quick start' 
4. Add Fleet-server host say `https//10.10.6.10:8220`
5. Copy the command in the cli.
7. Observe fleet-server is not installed.

**Expected Result:**
Fleet-server should be installed using Quick start 

**Screenshots:**
![image](https://user-images.githubusercontent.com/61860752/190339463-eb807e7a-dd32-41ee-8cd8-eae07362fa36.png)

Related issue: https://github.com/elastic/fleet-server/issues/1825

**Comment by amolnater-qasource** [comment] 2022-09-15 07:20
Secondary review for this issue is Done.

FYI @joshdover @jlind23

**Comment by jlind23** [comment] 2022-09-15 07:45
@amolnater-qasource seems to be a certificate issue. @michel-laterman @narph can one of you take a look at it please?

**Comment by narph** [comment] 2022-09-15 11:11
@amolnater-qasource , @deepikakeshav-qasource I've tried reproducing this on Windows 11 using:

https://snapshots.elastic.co/8.4.2-36096067/downloads/kibana/kibana-8.4.2-SNAPSHOT-windows-x86_64.zip with the commit you mentioned 
https://snapshots.elastic.co/8.4.2-36096067/downloads/elastic-agent/elastic-agent-8.4.2-SNAPSHOT-windows-x86_64.zip
https://snapshots.elastic.co/8.4.2-36096067/downloads/elasticsearch/elasticsearch-8.4.2-SNAPSHOT-windows-x86_64.zip

installed es and kibana, followed the steps you mentioned above and then ran:
```
PS C:\Users\MarianaDima\Desktop\test\test\842\elastic-agent-8.4.2-SNAPSHOT-windows-x86_64> .\elastic-agent.exe install `
>>   --fleet-server-es=http://localhost:9200 `
>>   --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NjMyMzkzMDQ4ODQ6Qi1OUlFXX3RRS09XNVFyVUJjY3daUQ `
>>   --fleet-server-policy=fleet-server-policy
Elastic Agent will be installed at C:\Program Files\Elastic\Agent and will run as a service. Do you want to continue? [Y/n]:y
{"log.level":"info","@timestamp":"2022-09-15T12:56:32.744+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":403},"message":"Generating self-signed certificate for Fleet Server","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-15T12:56:34.144+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":742},"message":"Waiting for Elastic Agent to start","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-15T12:56:36.148+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":792},"message":"Fleet Server - Starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-15T12:56:40.160+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":773},"message":"Fleet Server - Running on policy with Fleet Server integration: fleet-server-policy; missing config fleet.agent.id (expected during bootstrap process)","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-15T12:56:41.108+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":471},"message":"Starting enrollment to URL: https://DESKTOP-K76UDQL:8220/","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-15T12:56:42.273+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":273},"message":"Successfully triggered restart on running Elastic Agent.","ecs.version":"1.6.0"}
Successfully enrolled the Elastic Agent.
Elastic Agent has been successfully installed.
PS C:\Users\MarianaDima\Desktop\test\test\842\elastic-agent-8.4.2-SNAPSHOT-windows-x86_64>
```

Is there any step I might have missed during the test? Are those the right artifacts you have been using, can you still reproduce the issue?

**Comment by narph** [comment] 2022-09-15 11:19
I had a look at the issue you linked and I there the communication is encrypted, will test further with certificates but it's worth mentioning that the ticket description.

**Comment by amolnater-qasource** [comment] 2022-09-19 07:40
Hi @narph 
We have revalidated this issue on 8.5 Build Candidate Kibana self-managed environment and found this issue still reproducible:
- We are still not able to install Fleet server and getting x509 certificate error.

Further as per our observation for your comment https://github.com/elastic/fleet-server/issues/1869#issuecomment-1247953778
>   --fleet-server-es=http://localhost:9200

We have setup our kibana using Security on by default feature at link https://github.com/elastic/obs-infraobs-team/issues/565
So our elasticsearch is setup on `https`.

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/190964472-a65fa428-1597-47f9-8fba-c3c3d5c85736.JPG)

**Build details:**
8.4.2 BC1
BUILD: 55523
COMMIT: d34da2c98a97aac80c2b9e8ab197c76cc149574e

Please let us know if anything else is required from our end.
Thanks

**Comment by joshdover** [comment] 2022-09-19 11:34
@amolnater-qasource Are we sure this isn't expected behavior? I'd expect that Fleet Server would refuse to connect to an ES with a self-signed cert unless one of the following CLI flags are passed: `--insecure` or `--fleet-server-es-ca-fingerprint`

**Comment by narph** [comment] 2022-09-19 14:11
@amolnater-qasource , @joshdover took some time but I wanted to test this further.

I've configured tls/ssl for elasticsearch/kibana/fleet server and then ran the following:

```
 ./elastic-agent install --url=https://127.0.0.1:8220  --fleet-server-es=https://127.0.0.1:9200  --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NjM1OTQ2NjYyOTg6N1J0X2RvX2lTWXVpSEhpS0hxcWg1dw  --fleet-server-es-ca=C:\Users\...\Desktop\test\test\842\elasticsearch-8.4.2-SNAPSHOT\ca\ca.crt --certificate-authorities=C:\Users\...\Desktop\test\test\842\elasticsearch-8.4.2-SNAPSHOT\ca\ca.crt  --fleet-server-cert=C:\Users\...\Desktop\test\test\842\elasticsearch-8.4.2-SNAPSHOT\config\fleet-server.crt --fleet-server-cert-key=C:\Users\...\Desktop\test\test\842\elasticsearch-8.4.2-SNAPSHOT\config\fleet-server.key   --fleet-server-policy=fleet-server-policy
Elastic Agent will be installed at C:\Program Files\Elastic\Agent and will run as a service. Do you want to continue? [Y/n]:y
....
{"log.level":"info","@timestamp":"2022-09-19T15:54:04.749+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":273},"message":"Successfully triggered restart on running Elastic Agent.","ecs.version":"1.6.0"}
Successfully enrolled the Elastic Agent.
Elastic Agent has been successfully installed.
```
which means tls enabled should work.

then ran:

```
./elastic-agent install --url=https://127.0.01:8220  --fleet-server-es=https://127.0.0.1:9200    --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NjM1OTQ2NjYyOTg6N1J0X2RvX2lTWXVpSEhpS0hxcWg1dw  --fleet-server-policy=fleet-server-policy --insecure

Elastic Agent will be installed at C:\Program Files\Elastic\Agent and will run as a service. Do you want to continue? [Y/n]:
{"log.level":"info","@timestamp":"2022-09-19T16:01:12.342+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":403},"message":"Generating self-signed certificate for Fleet Server","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-19T16:01:13.827+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":759},"message":"Waiting for Elastic Agent to start Fleet Server","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-19T16:01:15.838+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":792},"message":"Fleet Server - Starting","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-19T16:01:19.849+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":792},"message":"Fleet Server - Error - x509: certificate signed by unknown authority","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-09-19T16:01:43.874+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":792},"message":"Fleet Server - Restarting","ecs.version":"1.6.0"}
Error: fleet-server failed: context canceled
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.4/fleet-troubleshooting.html
```

and got the same error as above.


then ran:
```
 ./elastic-agent install --url=https://127.0.01:8220  --fleet-server-es=https://127.0.0.1:9200    --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NjM1OTQ2NjYyOTg6N1J0X2RvX2lTWXVpSEhpS0hxcWg1dw  --fleet-server-policy=fleet-server-policy  --fleet-server-es-insecure

Elastic Agent will be installed at C:\Program Files\Elastic\Agent and will run as a service. Do you want to continue? [Y/n]:
{"log.level":"info","@timestamp":"2022-09-19T16:03:41.755+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":403},"message":"Generating self-signed certificate for Fleet Server","ecs.version":"1.6.0"}
...
{"log.level":"info","@timestamp":"2022-09-19T16:03:50.764+0200","log.origin":{"file.name":"cmd/enroll_cmd.go","file.line":273},"message":"Successfully triggered restart on running Elastic Agent.","ecs.version":"1.6.0"}
Successfully enrolled the Elastic Agent.
Elastic Agent has been successfully installed.

```

There are 2 separate flags here: `--insecure` and ` --fleet-server-es-insecure`

 --insecure                                        Allow insecure connection to fleet-server
--fleet-server-es-insecure                        Disables validation of certificates

When it comes bypassing es certificates the `--fleet-server-es-insecure` can be used. can you give it a try?

**Comment by amolnater-qasource** [comment] 2022-09-20 08:37
Hi @narph @joshdover 
Thank you for looking into this. 

We have revalidated this issue by running Fleet server installation command using `--fleet-server-es-insecure` and found it working fine.
- We are successfully able to install fleet server using `--fleet-server-es-insecure` flag.

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/191207249-94c1c886-7ad7-4097-ae52-d67ee3cbe508.JPG)


Further we have observed that fingerprint flag is missing from elasticsearch output and is also not available under Fleet Server install command. As per our understanding fingerprint flag should be available as per security on by default feature.

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/191207875-697efaa2-5d86-451c-b430-da58bcf87ddb.JPG)
![5](https://user-images.githubusercontent.com/77374876/191207884-d51ecd7c-616b-4018-85b4-11ba5ef40cf2.JPG)

We have revalidated the guide for [Fleet Server](https://www.elastic.co/guide/en/fleet/current/add-a-fleet-server.html) and observed that Fingerprint flag is available in installation command.

Please let us know if separate issue is required to be logged for this.

Thanks!

**Comment by narph** [comment] 2022-09-20 08:40
@amolnater-qasource can you create a separate issue regarding the fingerprint flag and the steps you are taking to reproduce it? it will be easier to follow on a separate thread

**Comment by amolnater-qasource** [comment] 2022-09-29 08:51
Hi @nchaulet 

We have attempted to install fleet server using `--fleet-server-es-insecure` flag on 8.5 BC2 Kibana self-managed environment and observed that fleet server gets stuck in updating state after running install command.

**Build details:**
VERSION: 8.5.0 BC2
BUILD: 56806
COMMIT: dc769f45a5a6dafb0a8c8f0c0cabcced4df45e11

**Screenshot:**
![1](https://user-images.githubusercontent.com/77374876/192985356-599d6e67-cc6b-4411-a77d-46ad798b6d01.JPG)


Thanks

**Comment by narph** [comment] 2022-09-29 10:41
@amolnater-qasource this only happens when using the --fleet-server-es-insecure flag? does it work when entering the certificates configuration?

**Comment by amolnater-qasource** [comment] 2022-09-29 10:51
Hi @narph 

We are unable to install fleet server without using ` --fleet-server-es-insecure` flag and actual reported issue is reproducible to us.
Further using --fleet-server-es-insecure it gets stuck in updating state as shared https://github.com/elastic/fleet-server/issues/1869#issuecomment-1261972290 .
Please let us know if anything else is required from our end.

Thanks

**Comment by joshdover** [comment] 2022-09-30 09:56
@nchaulet do you know what may be going on here?

**Comment by nathanatimu** [comment] 2022-10-03 13:39
Hi,
I'm facing also this issue. detail are provided here:
https://discuss.elastic.co/t/elastic-agent-error-dialing-x509-certificate-signed-by-unknown-authority/315675/3

in short: command:
`./elastic-agent install --url=https://ip-adress-of-other-server:8220 
--fleet-server-es=https://machine-host-name:9200 
--fleet-server-service-token=token 
--fleet-server-policy=fleet-server-policy 
--certificate-authorities=/etc/pki/elasticsearch/ca.crt 
--fleet-server-cert=/etc/pki/elasticsearch/fleet-server.crt 
--fleet-server-cert-key=/etc/pki/elasticsearch/fleet-server.key 
--fleet-server-es-insecure`

gives a a x509 error. while not expecting it here.

**Comment by cmacknz** [comment] 2022-10-03 14:25
Also seems to be reported in https://github.com/elastic/fleet-server/issues/1866

**Comment by nathanatimu** [comment] 2022-10-03 14:31
@cmacknz yeah, only difference is that the --fleet-server-es-insecure flag doesn't provide a solution

**Comment by nchaulet** [comment] 2022-10-03 14:36
> @nchaulet do you know what may be going on here?

The fact that the trusted fingerprint is missing is related to that bug https://github.com/elastic/kibana/pull/142109 

Using ` --fleet-server-es-insecure` seems to be the correct workaround, The fact that the agent is stuck in updating means the agent is not able to checkin, they should probably check the fleet server url here I saw this in the discussion that seems incorrect to me `url=https://127.0.01:8220`

**Comment by amolnater-qasource** [comment] 2022-10-04 09:33
Hi Team 
We have attempted to install fleet-server using production mode with certs and fleet server stuck in `Updating` state.
- We have run below command:
```
 .\elastic-agent.exe install --url=https://3.85.118.153:8220 `
   --fleet-server-es=https://172.31.20.150:9200 `
   --fleet-server-service-token=AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2NjQ4Njg2MjIyMDg6UWNDMGFnZnZTZTZVcXdmVy1yY3A5dw `
   --fleet-server-policy=fleet-server-policy `
   --certificate-authorities=C:\elk\elasticsearch\ca\ca.crt `
   --fleet-server-es-ca=C:\elk\elasticsearch\ca\ca.crt `
   --fleet-server-cert=C:\elk\elasticsearch\fleet-server\fleet-server.crt `
   --fleet-server-cert-key=C:\elk\elasticsearch\fleet-server\fleet-server.key --fleet-server-es-insecure
```

**Build details:**
```
BUILD: 56806
COMMIT: dc769f45a5a6dafb0a8c8f0c0cabcced4df45e11
```

**Screenshots:**
![1](https://user-images.githubusercontent.com/77374876/193778216-1675b77c-27bc-4752-bb04-923dba0ad970.JPG)
![2](https://user-images.githubusercontent.com/77374876/193778226-1b86cc72-2bfc-4299-a493-176f1fce82ad.JPG)

**Logs:**
[elastic-agent-diagnostics-2022-10-04T08-59-35Z-00.zip](https://github.com/elastic/fleet-server/files/9704337/elastic-agent-diagnostics-2022-10-04T08-59-35Z-00.zip)

Please let us know if we are missing anything.
Thanks

**Comment by narph** [comment] 2022-10-05 11:53
@amolnater-qasource looking at the errors in the logs you linked:

````
{"log.level":"info","@timestamp":"2022-10-04T08:59:15.451Z","log.origin":{"file.name":"operation/operator.go","file.line":387},"message":"operation 'operation-install' skipped for filebeat.8.5.0","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-10-04T08:59:16.030Z","log.origin":{"file.name":"status/reporter.go","file.line":326},"message":"Elastic Agent status changed to \"error\": \"app filebeat--8.5.0--36643631373035623733363936343635-dbac99b8: \\\"filebeat_monitoring\\\" failed to prepare monitor for \\\"Filebeat\\\": failed to create a directory \\\"\\\": mkdir : The system cannot find the path specified.\"","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-10-04T08:59:16.036Z","log.origin":{"file.name":"log/reporter.go","file.line":40},"message":"2022-10-04T08:59:16Z - message: Application: filebeat--8.5.0--36643631373035623733363936343635[944cd610-db45-42be-a49b-9681d0c614f5]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'","ecs.version":"1.6.0"}
```
I see they match the fix PR  https://github.com/elastic/elastic-agent/pull/1371 and issue https://github.com/elastic/fleet-server/issues/1934, I believe all should be good now. Let me know if you can still reproduce it after the fix

**Comment by amolnater-qasource** [comment] 2022-10-13 11:46
Hi Team
We have revalidated this on 8.5 BC4 kibana self-managed environment and found it **fixed now**.

**Observations:**
- Fleet-server is installed Healthy using Quickstart mode.

**Build details:**
BUILD: 57008
COMMIT: b2b4d5c5b4742fcfe5699dbcbffb9a98a5f06b5f

**Screenshots:**
![15](https://user-images.githubusercontent.com/77374876/195586043-24d1a8dd-23bb-490b-9127-171396309ed0.JPG)
![14](https://user-images.githubusercontent.com/77374876/195586076-2e67f7ff-a978-41fa-a1a8-5cfc281f1cae.JPG)

Hence we are **closing** this issue and are marking this issue as **QA:Validated**.
Thanks

**Closed by amolnater-qasource** 2022-10-13 11:46 UTC
Labels: bug, impact:high, Team:Elastic-Agent-Control-Plane

**Comment by simranvaseer-qasource** [comment] 2022-11-22 10:58
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/147843&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=30364
 
Thanks!
