### ISSUE TITLE
Not all agents are unenrolled after unenrollment timeout

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1635] opened 2022-07-05 11:15 UTC
**Kibana version:**  8.4 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
VERSION: 8.4.0 Snapshot
BUILD: 54160
COMMIT: b509d2466e88bf6c4386d8dd5fe89b5c8a54a97f
```

**Preconditions:**
1. 8.4 Snapshot Kibana cloud environment should be available.
2. Multiple agents should be installed.

**Steps to reproduce:**
1. Navigate to Fleet>Agents tab.
2. Set 10k multiple agents to same policy.
3. Set unenrollment timeout to 240 Seconds.
4. Turn off all the agents and observe all agents gone offline.
5. Observe all 10k agents take approximately 20 hours to unenroll from kibana.

**Expected Result:**
10k agents should not take approximately 20 hours while unenrolling  through unenrollment timeout.

**Screenshots:**
![16](https://user-images.githubusercontent.com/77374876/177315286-e3b10a90-4951-44e2-9b29-be9a45364246.JPG)
![17](https://user-images.githubusercontent.com/77374876/177315281-37c0ac8e-4e08-47b1-9de0-0a4cbfc6df30.JPG)

**Comment by michel-laterman** [comment] 2022-11-01 20:17
I think this may be caused by the query for offiline agents returning 10 at a time.
We can send a size or use a scroll parameter

**Comment by michel-laterman** [comment] 2022-11-09 19:39
https://github.com/elastic/kibana/issues/143455 will result in the removal of fleet-server unenrollment and will bypass this issue

**Comment by jlind23** [comment] 2022-11-23 15:48
Let's close this issue as this functionality will be removed from 8.7 on.

**Closed by jlind23** 2022-11-23 15:48 UTC
Labels: bug, Team:Elastic-Agent-Control-Plane, impact:medium

**Comment by amolnater-qasource** [comment] 2022-11-24 05:46
Hi Team,

Thank you for the update. 
We will be deprecating these test scenarios as soon as the unenrollment timeout functionality will be updated.

Thanks
