### ISSUE TITLE
Fleet Server Agent goes offline on inactivity.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#251] opened 2021-04-20 07:53 UTC
**Kibana version:** 7.13.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** Windows 10 x64, All

**Build Details:**
```
  Artifact link used: https://snapshots.elastic.co/7.13.0-a6f186fd/downloads/beats/elastic-agent/elastic-agent-7.13.0-SNAPSHOT-windows-x86_64.zip
  Build: 40404
  Commit: 58cbb76568e50d72fdcccc5b1e055dbc27820aa5
```

**Preconditions:**
1. 7.13.0 Snapshot Kibana cloud environment should be available.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Add "Fleet Server host" url under "Fleet Settings".
3. Run fleet server installation command:
```
 .\elastic-agent install --fleet-server-es=https://elastic:ZnSHL0mDC7S3LSqHxxxxxxx@security-deployment-xxxxxx.es.us-central1.gcp.foundit.no:9243
```

**Note:**
-  On restarting Elastic Agent from services Fleet Server Agent gets back to healthy state.

**Expected Result:**
Fleet Server Agent should not go offline on inactivity.

**Elastic Agent Logs:**
[logs.zip](https://github.com/elastic/fleet-server/files/6341619/logs.zip)

**Screenshot:**
![11](https://user-images.githubusercontent.com/77374876/115358328-2d9b6300-a1db-11eb-9b36-a99e95b36b04.JPG)

**Comment by manishgupta-qasource** [comment] 2021-04-20 12:50
Reviewed & Assigned to @EricDavisX

**Comment by amolnater-qasource** [comment] 2021-04-26 10:07
Hi @EricDavisX 
Today while testing on 7.13 BC-2 self managed Kibana, we have observed similar issue.
On inactivity Fleet Server agent goes to **offline** state. 

**Build details:**
```
Artifact link used: https://staging.elastic.co/7.13.0-24571870/summary-7.13.0.html
Build: 40598
Commit: a2f386b628764ea82af0893b8e25a16290dd6f44
```

**Screenshot:**
![7](https://user-images.githubusercontent.com/77374876/116063138-3fc94580-a6a2-11eb-8755-ced993893082.JPG)

**Comment by blakerouse** [comment] 2021-04-27 11:38
@amolnater-qasource I reviewed the `logs.zip` file attached. It only contains the `elastic-agent.log*`. That only tells one side of the story. Could you also provide the `logs` directory that includes the logs for `fleet-server`?

**Comment by amolnater-qasource** [comment] 2021-04-27 11:55
Hi @blakerouse 
Please find logs for `fleet-server` below:
[default.zip](https://github.com/elastic/fleet-server/files/6384267/default.zip)

Thanks
QAS

**Comment by dikshachauhan-qasource** [comment] 2021-04-28 13:05
Hi @EricDavisX 

This issue is still observable on 7.13 Kibana Staging cloud build. Agent keeps on switching it state itself between healthy and offline.

Build details:
BUILD 40647
COMMIT ac09c73a4a7998c770b50d39177c22036ae14375

Please let us know if any updates are available to make fixes around this behavior.

Thanks
QAS

**Comment by EricDavisX** [comment] 2021-04-28 17:39
@blakerouse I know Ruflin had offered an env to reproduce this, I see Amol has attached more logs - anything you need from us?  Any update as you research?

**Comment by dikshachauhan-qasource** [comment] 2021-04-30 13:12
Hi @EricDavisX 

Today while performing testing on cloud-qa environments, we observed above reported issue as reproducible.

- On inactivity for some time say an hour or above Fleet Server Agent goes offline and status remains as offline though datastream continues to add up.

We attempted to restart agent services, assigned a new policy and also restarted Kibana. However, any action performed could not update agent status.

Please let us know if anything else is required.

[fleet-server-json.log](https://github.com/elastic/fleet-server/files/6405540/fleet-server-json.log)
[elastic-agent-json.log](https://github.com/elastic/fleet-server/files/6405541/elastic-agent-json.log)


Thanks
QAS

**Comment by blakerouse** [comment] 2021-04-30 13:38
I am able to reproduce it, I am currently still trying to figure out why.

**Comment by blakerouse** [comment] 2021-05-03 15:12
This is because of #23839 not being backported to 7.x or 7.13.

**Comment by blakerouse** [comment] 2021-05-03 18:07
This is fixed, with the backport being merged.

https://github.com/elastic/beats/pull/25498

**Closed by blakerouse** 2021-05-03 18:07 UTC
Labels: Team:Agent, bug, v7.13.0
