### ISSUE TITLE
Seeing 401 errors in fleet-server logs

### ISSUE THREAD

**Issue by simitt** [elastic/fleet-server#217] opened 2021-04-12 12:49 UTC
**Version**: master/7.13 snapshots

**Issue**
Starting an Elastic Agent docker container with Fleet-Server setup enabled, results in `401` errors in the Fleet Server. 

**Steps to reproduce**:
 1. Set up an ES and Kibana instance based off `7.13-SNAPSHOT`.
 2. Set up an Elastic Agent container with Fleet Server setup enabled, that cannot be reached from Kibana and Elasticsearch.  
```
docker run --group-add 0 \
  --env STATE_PATH=/myapp/elastic-agent \
  --env CONFIG_PATH=/myapp/config \
  --env LOGS_PATH="/myapp/logs" \
  --env HOME_PATH="/myapp" \
  -p 8220:8220  \
  -v <path-to-myapp>:/myapp --rm docker.elastic.co/beats/elastic-agent:7.13.0-SNAPSHOT
```
where the `<path-to-myapp>` directory is of following structure 
```
|- config
   |- fleet-setup.yml
|- elastic-agent
|- logs
```
and `config/fleet-setup.yml`:
```
fleet:
  enroll: true
  force: false
  insecure: true
fleet_server:
  enable: true
  host: "0.0.0.0" 
  insecure_http: true
kibana:
  fleet:
    setup: true
```
 3. Check Fleet Server logs to contain following errors:
```
{"log.level":"info","error":"fail Auth: [401 Unauthorized] {\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/_security/_authenticate]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/_security/_authenticate]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}},\"status\":401}","id":"5611a9f4-57b5-4e54-a03c-c7e757711ef8","code":400,"@timestamp":"2021-04-12T10:55:59.021Z","message":"fail checkin"}
```

Configuring the `fleet-server` url in the Kibana setup does not fix anything.

**Comment by simitt** [comment] 2021-04-12 18:46
So far the issue can only be reproduced on an AWS instance (set up using the Ubuntu AMI described in the [ece-configuration](https://www.elastic.co/guide/en/cloud-enterprise/current/ece-configure-ami.html)).

After debugging this with @blakerouse it turned out that the setting `fleet_server.insecure_http: true` caused the issues. When setting to `false` everything works as expected. Issues were seen with current `master` and `7.13` snapshots.

**Comment by scunningham** [comment] 2021-04-13 18:56
@simitt ok to close this?

**Comment by simitt** [comment] 2021-04-13 20:19
No, the issue still exists when `fleet_server.insecure_http: true`; figuring out that the setting was the root cause did unblock e though.

**Comment by blakerouse** [comment] 2021-04-13 20:45
With `fleet_sever.insecure_http: true` I am unable to reproduce this. I have not been able to determine what makes @simitt setup different than mine and causing it to fail.

**Comment by michel-laterman** [comment] 2023-02-27 16:10
I'm going to close this as it's for an old version

**Closed by michel-laterman** 2023-02-27 16:10 UTC
