### ISSUE TITLE
[Self-managed]: Unable to install fleet-server using Quick start and Production mode.

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/fleet-server#1825] opened 2022-09-05 05:17 UTC
Kibana version: 8.5 Snapshot Kibana self-managed environment

Host OS and Browser version: Windows, All

**Build details:**
VERSION: 8.5 Snapshot self-managed
BUILD: 55993
COMMIT: 436b2874794a6ffc05ad3b9ef28c298ff5384ca4

**Preconditions:**
- 8.5 Snapshot Kibana self-managed environment should be available.

**Steps to reproduce:**
1. On fresh Kibana setup navigate to Fleet tab.
2. Create Fleet Server Policy.
3. Select 'Quick start' or 'Production Mode'.
4. Add Fleet-server host say `https//10.10.10.10:8220`
5. Copy the command in the cli.
7. Observe fleet-server is not installed.

**Expected Result:**
Fleet-server should be installed using Quick start and Production mode.

**Screenshots:**
Quick start:
![image](https://user-images.githubusercontent.com/102019374/188364795-ecd7528d-4a6e-496a-9453-0b683f8b47de.png)

Production Mode:
![image](https://user-images.githubusercontent.com/102019374/188364832-55ef0b85-f2b5-454d-b48a-63ccf329c8e6.png)

**Comment by dikshachauhan-qasource** [comment] 2022-09-05 05:37
Secondary review is done

**Comment by joshdover** [comment] 2022-09-14 11:22
FYI @jen-huang and @kpollich

**Comment by kpollich** [comment] 2022-09-14 15:00
I see an `x509 - Certificate signed by unknown authority` error in the quick start logs. Confusing since Fleet Server should be generating its own cert in this context.

**Comment by amolnater-qasource** [comment] 2022-09-15 07:27
Hi @kpollich 

We have observed this issue reproducible on 8.4.2 BC1 self-managed environment and reported a separate issue at https://github.com/elastic/fleet-server/issues/1869

Thanks

**Comment by kpollich** [comment] 2022-09-15 12:00
Closing in favor of https://github.com/elastic/fleet-server/issues/1869 - please reopen if needed.

**Closed by kpollich** 2022-09-15 12:00 UTC
Labels: bug, Team:Fleet, impact:high

**Comment by simranvaseer-qasource** [comment] 2022-11-22 10:58
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:

- https://elastic.testrail.io/index.php?/cases/view/147843&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=30364

Thanks
