### ISSUE TITLE
starting and stopping agents from fleet servers 

### ISSUE THREAD

**Issue by allamiro** [elastic/fleet-server#2311] opened 2023-02-02 10:40 UTC
If you manage large numbers of elastic agents across multiple locations and data centers it would nice to have the ability to restart start stop the agents  remotely from the fleet server using the actions button. The only options available there is Upgrade , Enroll  and Add integration policies . 

The Agent Activity under fleet section showing the activity log is not showing what host that has the agent installed  is upgraded or enrolled etc it would be nice to have the hostname or IP alongside the activity itself.

**Comment by jlind23** [comment] 2023-02-02 13:28
@allamiro thanks for creating this issue, I believe this is a duplicate of https://github.com/elastic/kibana/issues/144585 do you agree with that?

**Closed** 2023-02-02 20:13 UTC
