### ISSUE TITLE
[Fleet Server][Agent]: All already-installed agents go unhealthy when user adds a new Fleet Server (self managed relating work flow).

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#563] opened 2021-07-16 11:49 UTC
**Kibana version:** 7.14.0 BC-3 Kibana cloud environment

**Host OS and Browser version:** All agents, Windows Fleet Server, All

**Build details:**
```
Build: 42545
Commit c314921a9893e0b46d9a3958f5520e3d6b1ce7d5
Artifact Link: https://staging.elastic.co/7.14.0-682a8012/summary-7.14.0.html
```

**Preconditions:**
1. 7.14.0 BC-3 Kibana cloud environment should be available.
2. Few Agents must be installed using Default policy having System Integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Add Fleet server integration in a policy and navigate to Agents tab.
3. Click Add Agent button and Add Host ip on which you are going to install Fleet Server(https://10.10.10.10:8220).
4. Observe all the existing agents went to "Unhealthy" state.
5. Run Fleet Server install command and observe fleet server is installed Healthy.
6. However, all pre-installed agents remain "Unhealthy". 

**Expected Result:**
Pre-installed Agents should not go unhealthy on adding Fleet Server. 

**Pre-installed Windows agent logs:**
[logs.zip](https://github.com/elastic/fleet-server/files/6830374/logs.zip)

**Screenshot**
![17](https://user-images.githubusercontent.com/77374876/125942548-2f1d1625-e533-4ec3-8a2c-ccea889bfab4.JPG)

**Fleet Settings:**

![18](https://user-images.githubusercontent.com/77374876/125942998-b6602f8a-f657-49d5-b7b8-fcab078bbd50.JPG)

**Note:**
We are able to reproduce this issue on two different staging environments.

**Comment by amolnater-qasource** [comment] 2021-07-16 11:49
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2021-07-16 12:02
Reviewed & assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2021-07-19 12:57
This is the combined / hybrid cloud stack and local Fleet Server environment - it is tbd if it is fully supported currently, we're testing and looking for bugs.  

This would seem to indicate the Agents are doing a reconnection as soon as the Fleet Server kibana value is changed, is that the correct action?   Maybe @blakerouse can comment?  

Either way, it isn't ideal, if we agree to release with this we could put it as a known bug (not sure how to make that happen).

**Comment by blakerouse** [comment] 2021-07-19 13:09
This is expected behavior. You cannot add the `fleet-server` integration to an existing Policy that already has Elastic Agents enrolled. An Elastic Agent cannot just bring up a Fleet Server, that is because that Fleet Server needs a service token for it to connect. The only way to provide a service token is when the `install` or `enroll` command. So if you want to add the Fleet Server integration to a policy that already has Elastic Agent's running then you will need to re-enroll those Elastic Agent's using the `--fleet-server-es` and the `--fleet-server-service-token` flags.

**Comment by amolnater-qasource** [comment] 2021-07-19 13:47
Hi @blakerouse 
> You cannot add the fleet-server integration to an existing Policy that already has Elastic Agents enrolled.

We have not added Fleet server integration to the existing policy with agents. All agents were installed with Default policy and we added Fleet Server in the policy name "Amol Policy" with which we have installed the Fleet Server and also looks Healthy.

Please refer below screenshot for further clarity:
![6](https://user-images.githubusercontent.com/77374876/126169282-85583de9-236d-4ef7-ac13-ce03d334f62c.jpg)

Further this issue was observed just after adding https://fleet-server-ip:8220.

We attempted to install Fleet-Server and check if it make agents Healthy. However it didn't connect to it and remained **Unhealthy**.

cc: @EricDavisX 
Thanks
QAS

**Comment by blakerouse** [comment] 2021-07-19 14:02
@amolnater-qasource Did you add that Fleet Server connection information to the `Fleet Server URL` `Fleet settings` fly out?

**Comment by EricDavisX** [comment] 2021-07-19 14:47
Yes, it looks like he did, it is shown in the initial screenshots.  @blakerouse

**Comment by blakerouse** [comment] 2021-07-19 15:03
Okay then it seems possible that they are reporting unhealthy because of communication issues with that new Fleet Server. That should not be the case as if an Elastic Agent cannot communicate with a Fleet Server it will fallback to one that it can communicate and I do not believe that it should cause the Elastic Agent to report unhealthy.

Based on the logs, it is because the Fleet Server you bootstrapped is using a self-signed certificate. That is why your logs show `x509: certificate signed by unknown authority`.

Really it depends on the behavior you're looking for here. Are you expecting those Elastic Agents to be able to communicate with the new Fleet Server? If so then you need to re-enroll those Elastic Agent's with the `--insecure` flag (even if its secure to the Fleet Server run by cloud), that way the new Fleet Server can be communicated with. Or you setup your Fleet Server on a real-domain with a real certificate with a full CA verifiable chain.

If your are expecting those Elastic Agent's to not be able to communicate because it is not secure and they stay reporting healthy, then I believe we have a bug that we need to look into.

**Comment by amolnater-qasource** [comment] 2021-07-20 10:45
Hi @blakerouse 
Thanks for your feedback.
> If so then you need to re-enroll those Elastic Agent's with the --insecure flag

We installed few agents with `--insecure` flag and they remained Healthy on adding multiple URL's under Fleet Settings.

**Screenshot:**
![14](https://user-images.githubusercontent.com/77374876/126310179-bd782b29-ed10-40f2-9d2c-c8d878087228.JPG)

Hence we are **closing** this issue, as it is working fine.

Thanks
QAS

**Comment by EricDavisX** [comment] 2021-07-20 13:05
This is a good scenario to question.  I'd like to pull in @mostlyjason and @nimarezainia for their input.  

I have more questions, myself:  
 I wonder what actions / timing triggers an Agent to attempt to connect to a different fleet server?  In the scenario the test team presents, it seems to make sense (and be expected) that setting up an additional fleet Server wouldn't impact existing connected and happy healthy Agents.  But, I think I saw that the design is such that on an every 30 seconds timer, the Agent will check for any new Fleet Servers.  If that is the current design, we may want to improve the design as it would make it particularly challenging to set up new Fleet Servers self-managed instances (one mistake and all agents go unhealthy is not 'enterprise' stable in my opinion).  It would make it harder to be successful scaling Fleet server out, right?

I don't know how much we want to invest here.  The option noted above of knowing to install all Agents as --insecure may work, but seems an inappropriate solution if they are intending to be production.  Some work may benefit us to make it easier and less scary / error prone for self-managed relating Fleet Server usage.  I did a quick test with cloud scale of 1 to 2 to 3 (and back to 2) zones for multiple fleet-servers to be stood up and it did NOT send all agents unhealthy / off-line with every change.

**Comment by EricDavisX** [comment] 2021-07-20 13:05
I've briefly re-open this for discussion.  we can close it back when desired.

**Comment by blakerouse** [comment] 2021-07-21 14:05
In a production situation you would never enroll with `--insecure` and you would also not setup a production Fleet server that is not full TLS.

So the question really is should Elastic Agent that was installed without `--insecure`, should it ignore Fleet Servers that are not secure and only connect to those that are secure. Negative is that it might not be obvious that none of the Elastic Agent's will connect to that Fleet Server.

**Comment by mostlyjason** [comment] 2021-07-22 14:16
Maybe we can just document that we expect all the fleet servers to be secure or insecure, that we don't support blended models? We could do that here https://github.com/elastic/observability-docs/issues/523? 

If that works, we can close this as won't fix.

**Comment by blakerouse** [comment] 2021-07-22 15:58
@mostlyjason Or if you want mixed you need to enroll all your agents with `--insecure`. I think that would be acceptable and we can set it to won't fix.

**Comment by nimarezainia** [comment] 2021-07-22 16:20
@mostlyjason @blakerouse tbh mixed makes no sense to me. it needs to be secure all the time. (i realize that all agents can be --insecure but i don't think we want this to be the default position).

I suggest we close this and keep an eye on what the customer feedback is in this regard.

**Comment by EricDavisX** [comment] 2021-07-22 17:46
I agree - closing it out, again.

**Closed by EricDavisX** 2021-07-22 17:46 UTC
Labels: Team:Agent, Team:Fleet, bug
