### ISSUE TITLE
[Deployment]: Hosted Fleet Server is not available under Fleet> Agents Tab on 8.6 SNAPSHOT

### ISSUE THREAD

**Issue by prachigupta-qasource** [elastic/fleet-server#2076] opened 2022-11-14 04:29 UTC
**Description:**
- `Hosted Fleet Server` is not available under `Fleet> Agents` Tab on 8.6 SNAPSHOT.

  - https://staging.found.no/deployments/create

**Platform:**
Google Cloud Platform

**Observations:**

- Build is `Healthy with Warnings`.
- `Hosted Fleet Server` is not available under `Fleet> Agents` Tab.

**Screenshots:**

![image](https://user-images.githubusercontent.com/97870262/201574732-9bec9bc5-9bbd-4f4f-bf17-3e9bf995541e.png)

![image](https://user-images.githubusercontent.com/97870262/201574479-d0e204d8-0596-4dff-99e1-80b20b9ca822.png)

![image](https://user-images.githubusercontent.com/97870262/201574918-d4f21b80-fd71-4550-9c72-96c44c71fed0.png)

**Comment by amolnater-qasource** [comment] 2022-11-14 04:32
Secondary review for this ticket is Done.

FYI @cmacknz

**Comment by cmacknz** [comment] 2022-11-14 18:56
Probably a duplicate of https://github.com/elastic/elastic-agent/issues/1712. We will need to retest with a snapshot build that includes https://github.com/elastic/elastic-agent/commit/8eb334aa6731afacf7161edfd33f5915a5a6b3ba

**Comment by amolnater-qasource** [comment] 2022-11-16 06:37
Hi @cmacknz 
We have attempted to redeploy latest 8.6 SNAPSHOT kibana cloud-staging environment and had below observations:
- APM & Fleet settings still failed.
- Hosted fleet server is available, however it goes offline after sometime.

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/202102832-9d638493-f8d8-4a47-9a42-b3fd0818cc3f.JPG)
![4](https://user-images.githubusercontent.com/77374876/202102853-b5eb10e8-bd9e-42bb-a0ea-c01c6c2678b8.JPG)

**Build details:**
BUILD: 58247
COMMIT: f893523d63e99d623269969af3f611ddff36c1c1

Please let us know if anything else is required from our end.
Thanks

**Comment by amolnater-qasource** [comment] 2022-11-17 11:01
Hi Team,

We have attempted to redeploy latest 8.6 BC1 kibana cloud-production environment and had below observations:
- APM & Fleet settings failed.
- Hosted fleet server is available, however it goes offline after sometime.

**Build details:**
BUILD: 58392
COMMIT: 50a7feb0a5eb068d3acccc49c83b9ccb6db6734f

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/202412135-fdadac72-756e-4f86-b734-d1ce6197d23e.png)
![image](https://user-images.githubusercontent.com/77374876/202412196-d2cefeed-7d20-4bd2-8ea6-e5efd9bd885b.png)

Thanks

**Comment by cmacknz** [comment] 2022-11-21 15:58
@joshdover I suspect your comment was meant to be on https://github.com/elastic/elastic-agent/issues/1756 since there is no API key error on this one.

**Comment by joshdover** [comment] 2022-11-22 13:24
🤦 yes, too many issue tabs

**Comment by amolnater-qasource** [comment] 2022-11-23 12:32
Hi Team,

We have attempted to redeploy latest 8.6 BC2 kibana cloud-production environment and had below observations:
- APM & Fleet settings failed.
- Hosted fleet server is available, however it goes offline after sometime.

**Build details:**
BUILD: 58485
COMMIT: b52b34c2ff5216c395bd49c5fbc97744b646f34d

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/203536733-b9cc5494-189b-4d7a-83d0-6983893b33cd.png)
![image](https://user-images.githubusercontent.com/77374876/203537770-c0e1738b-fe32-4fce-9de9-7bf38c6625c9.png)


Thanks

**Closed** 2022-11-23 16:19 UTC
Labels: bug, impact:high, Team:Elastic-Agent-Control-Plane, v8.6.0

**Comment by amolnater-qasource** [comment] 2022-11-29 10:13
Hi Team,

We have attempted to redeploy latest 8.6 BC3 kibana cloud-production environment and had below observations:
- Hosted fleet server is available.
- Fleet settings are working, however APM settings are still failing.

**Build details:**
BUILD: 58485
COMMIT: b52b34c2ff5216c395bd49c5fbc97744b646f34d

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/204487552-f9504196-c185-45d7-8b45-ca2f0333580a.png)
![image](https://user-images.githubusercontent.com/77374876/204487642-4ab725e4-6737-4c4c-aaca-3b9ed6d0b598.png)

Hence we are marking this as QA:Validated.

Thanks

**Comment by prachigupta-qasource** [comment] 2023-01-23 10:00
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/tests/view/1893570
 
Thanks!
