### ISSUE TITLE
Changing log level in Kibana UI of Agent with Fleet Server causes problem

### ISSUE THREAD

**Issue by EricDavisX** [elastic/fleet-server#271] opened 2021-04-23 18:36 UTC
Using the latest 8.0 artifacts as of April 23 I am seeing a Fleet Server come on line and show logging in the Kibana UI.  When I update the Agent from 'INFO' to 'DEBUG' log level it seems to stop ingesting logs in the UI - it is possible the timing is just coincidental.  Either way I can attach the logs I see on the host, that are not showing in Kibana.

Kibana is self-managed snapshot deploy commit:
commit f094d9fdc23d0bc393c072b96e437cdefc12bc4f
Date:   Thu Apr 22 12:50:35 2021 +0100

Agent artifacts are deployed to debian9 in GCP
elastic-agent version yields:
Binary: 8.0.0-SNAPSHOT (build: 43280e0f690bdacca03d313bd3121247833854ea at 2021-04-22 16:20:05 +0000 UTC)

when I change the Agent log level to ‘debug’ it looks like Fleet Server stopped logging stuff… do we think that is hooked up yet or no?   I’m seeing newer logs on the host than are showing in Kibana UI…

here is the last log line from host:
{“log.level”:“debug”,“agentId”:“116bd78e-30a2-4884-ad3e-58411e56e10f”,“sz”:0,“@timestamp”:“2021-04-23T18:25:10.657Z”,“message”:“Unsubscribed from action dispatcher”}

Here is the Fleet Server log snippet from the host, the last line is at INFO level and is the last seen in the 

```
{“log.level”:“info”,“status”:“HEALTHY”,“@timestamp”:“2021-04-23T18:10:07.666Z”,“message”:“Running on policy with Fleet Server integration: c6ac67d0-a418-11eb-a4bb-ddac73bf3875"}
{“log.level”:“debug”,“@timestamp”:“2021-04-23T18:10:07.666Z”,“message”:“Policy self monitor exited”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:10:23.686Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:10:45.249Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:11:06.809Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:11:28.369Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:11:50.405Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:12:11.969Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:12:34.394Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:12:55.958Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:13:17.52Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:13:39.09Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:14:00.655Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:14:22.432Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:14:43.99Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“index”:“.fleet-policies”,“ctx”:“index monitor”,“@timestamp”:“2021-04-23T18:15:02.097Z”,“message”:“timeout on global checkpoints advance, poll again”}
{“log.level”:“debug”,“index”:“.fleet-actions”,“ctx”:“index monitor”,“@timestamp”:“2021-04-23T18:15:02.097Z”,“message”:“timeout on global checkpoints advance, poll again”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:15:05.557Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“agentId”:“116bd78e-30a2-4884-ad3e-58411e56e10f”,“sz”:0,“@timestamp”:“2021-04-23T18:15:06.302Z”,“message”:“Unsubscribed from action dispatcher”}
{“log.level”:“debug”,“token”:“927cc9c1-c6ce-4746-8909-1883924eb4fc”,“seqno”:1,“@timestamp”:“2021-04-23T18:15:08.617Z”,“message”:“Found token cached”}
{“log.level”:“debug”,“agentId”:“116bd78e-30a2-4884-ad3e-58411e56e10f”,“sz”:1,“@timestamp”:“2021-04-23T18:15:08.617Z”,“message”:“Subscribed to action dispatcher”}
{“log.level”:“debug”,“ctx”:“policy agent monitor”,“agentId”:“116bd78e-30a2-4884-ad3e-58411e56e10f”,“policyId”:“c6ac67d0-a418-11eb-a4bb-ddac73bf3875”,“revno”:5,“coordno”:1,“@timestamp”:“2021-04-23T18:15:08.617Z”,“message”:“subscribed to policy monitor”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:15:27.124Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:15:48.692Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:16:10.473Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:16:32.036Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:16:54.526Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:17:16.093Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:17:38.511Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:18:00.076Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:18:22.563Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:18:44.131Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:19:05.69Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:19:27.251Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:19:48.816Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“index”:“.fleet-policies”,“ctx”:“index monitor”,“@timestamp”:“2021-04-23T18:20:02.103Z”,“message”:“timeout on global checkpoints advance, poll again”}
{“log.level”:“debug”,“index”:“.fleet-actions”,“ctx”:“index monitor”,“@timestamp”:“2021-04-23T18:20:02.119Z”,“message”:“timeout on global checkpoints advance, poll again”}
{“log.level”:“debug”,“agentId”:“116bd78e-30a2-4884-ad3e-58411e56e10f”,“sz”:0,“@timestamp”:“2021-04-23T18:20:08.618Z”,“message”:“Unsubscribed from action dispatcher”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:20:10.379Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“token”:“927cc9c1-c6ce-4746-8909-1883924eb4fc”,“seqno”:1,“@timestamp”:“2021-04-23T18:20:10.656Z”,“message”:“Found token cached”}
{“log.level”:“debug”,“agentId”:“116bd78e-30a2{“log.level”:“debug”,“agentId”:“116bd78e-30a2-4884-ad3e-58411e56e10f”,“sz”:1,“@timestamp”:“2021-04-23T18:20:10.656Z”,“message”:“Subscribed to action dispatcher”}
{“log.level”:“debug”,“ctx”:“policy agent monitor”,“agentId”:“116bd78e-30a2-4884-ad3e-58411e56e10f”,“policyId”:“c6ac67d0-a418-11eb-a4bb-ddac73bf3875”,“revno”:5,“coordno”:1,“@timestamp”:“2021-04-23T18:20:10.656Z”,“message”:“subscribed to policy monitor”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:20:31.747Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:20:53.587Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:21:15.159Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:21:37.641Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:21:59.196Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:22:20.762Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:22:42.329Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:23:03.672Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:23:25.23Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“index”:“.fleet-actions”,“ctx”:“index monitor”,“checkpoints”:[2],“@timestamp”:“2021-04-23T18:23:41.715Z”,“message”:“updated checkpoint”}
{“log.level”:“debug”,“agent_id”:“f273d57c-9700-4954-ba87-918e7495ecf2",“@timestamp”:“2021-04-23T18:23:41.715Z”,“message”:“Agent is not currently connected. Not dispatching actions.“}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:23:46.792Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:24:08.357Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:24:29.922Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“ctx”:“policy leader manager”,“@timestamp”:“2021-04-23T18:24:51.667Z”,“message”:“ensuring leadership of policies”}
{“log.level”:“debug”,“index”:“.fleet-policies”,“ctx”:“index monitor”,“@timestamp”:“2021-04-23T18:25:02.109Z”,“message”:“timeout on global checkpoints advance, poll again”}
{“log.level”:“debug”,“agentId”:“116bd78e-30a2-4884-ad3e-58411e56e10f”,“sz”:0,“@timestamp”:“2021-04-23T18:25:10.657Z”,“message”:“Unsubscribed from action dispatcher”}
```

**Comment by ruflin** [comment] 2021-04-26 08:05
I'l marked this as 7.13 as I'm pretty sure the exact same thing exists in 7.13

**Comment by ph** [comment] 2021-04-28 15:08
I wonder it this is not due to the problem with having Agent going healthy / unhealthy.
Or fleet server doesn't support updating his log level?

@scunningham @aleksmaus Can you confirm?

**Comment by scunningham** [comment] 2021-04-28 15:20
Fleet server does support log level change.  The configuration comes in from the agent.  Do we have some indication from the agent what configuration it is sending to the fleet server?

Not clear what's going on here.  Reproducible?

**Comment by ph** [comment] 2021-04-28 15:40
@urso  Can you take a look at this one to bring clarify? I think th e main issue is either: 1. we doesn't send the configuration to fleet-server or we doesn't restart doesn't work on this process.

**Comment by kvch** [comment] 2021-05-13 07:58
I have tested it with the latest 7.13 snapshot and it works as expected.

**Comment by kvch** [comment] 2021-05-14 10:34
As @michalpristas pointed it out, logging is not enabled by default, so the behaviour is OK.

**Comment by scunningham** [comment] 2021-05-14 13:22
I've seen similar issue in cloud qa.

1) Create a security cluster, add 24 gb fleet/apm capacity.
2) Create a metrics cluster for observabitliy.
3) Redirect logs/metrics from the security cluster to the metrics cluster using the qa.cloud console.
4) Navigate to one of the 3 agents in kibana->fleet, switch the logging from info to debug an apply
5) Note that the agent goes offline, and we see errors in the agent log (see pics below)

![Screen Shot 2021-05-14 at 9 18 05 AM](https://user-images.githubusercontent.com/294689/118276630-e16bd780-b495-11eb-941f-d2d05d593299.png)

![Screen Shot 2021-05-14 at 9 14 43 AM](https://user-images.githubusercontent.com/294689/118276706-ee88c680-b495-11eb-8785-4d4abea1c8da.png)

**Comment by ph** [comment] 2021-05-14 13:38
@scunningham can you add the Agent policy in this issue?

**Comment by scunningham** [comment] 2021-05-14 13:50
It is in a weird state.  The other two agents are still healthy, but the one I targeted remains "offline".  The policy doesn't seem to have changed; nothing related to log change in the "Elastic Cloud agent policy".

<<
id: elastic-agent-on-cloud
revision: 2
outputs:
  default:
    type: elasticsearch
    hosts:
      - >-
        https://c0214f7c34f7460fa378c373baf8d74b.us-central1.gcp.qa.cld.elstc.co:443
output_permissions:
  default:
    _fallback:
      cluster:
        - monitor
      indices:
        - names:
            - logs-*
            - metrics-*
            - traces-*
            - .logs-endpoint.diagnostic.collection-*
            - synthetics-*
          privileges:
            - auto_configure
            - create_doc
agent:
  monitoring:
    enabled: false
    logs: false
    metrics: false
inputs:
  - id: 3f7a1443-b07d-4cb5-94c4-2e76b3e2f87a
    name: Fleet Server
    revision: 1
    type: fleet-server
    use_output: default
    meta:
      package:
        name: fleet_server
        version: 0.2.3
    data_stream:
      namespace: default
    server:
      port: 8220
      host: 0.0.0.0
fleet:
  hosts:
    - >-
      https://d71426f53ce1474db9e719740979bbae.fleet.us-central1.gcp.qa.cld.elstc.co:443
>>

**Comment by ph** [comment] 2021-05-14 14:19
@scunningham Hmm this looks strange, there is not output configuration in that agent policy, did you remove it ?

**Comment by blakerouse** [comment] 2021-05-14 14:24
@scunningham can you attach the `state.yml` from the Elastic Agent that is having that issue? does a restart of the Elastic Agent keep showing the same error?

**Comment by scunningham** [comment] 2021-05-14 14:25
Not sure how to get that.  It's in cloud; i don't have direct access.

**Comment by EricDavisX** [comment] 2021-05-14 19:24
[Archive.zip](https://github.com/elastic/fleet-server/files/6480800/Archive.zip)
here is a zip of the fleet.yml (and the old fleet.yml) from a host running Fleet Server that we believe is having the same problem (it was restarted and stopped sending logs to ES)

**Comment by kvch** [comment] 2021-05-18 11:20
It is no longer an issue.

**Closed by kvch** 2021-05-18 11:20 UTC
Labels: Team:Agent, blocker, bug, v7.13.0

**Comment by ruflin** [comment] 2021-05-18 11:30
@kvch Can you please provide some more details on where and how it was fixed and how to test it?

**Comment by kvch** [comment] 2021-05-18 11:40
The root cause of the problem is the same as in https://github.com/elastic/beats/issues/25709. The input configuration was incorrect, the Fleet server has stopped sending its logs after the configuration change.

I had tested it on the latest snapshot on Friday.
First phase:
1. Enroll an Agent
2. Enable Fleet logging
Check: Fleet is sending its logs

Second phase:
1. Change log level from info to debug on the Logs tab of the Agent
Check: Fleet is still sending its logs

In my testing the two checks were successful.

**Comment by ruflin** [comment] 2021-05-18 11:46
I see https://github.com/elastic/beats/issues/25709 is still open. Does it mean this one should be closed too? What you mean by input configuration was incorrect? Which part and was it user error or something we fixed on the code side?

**Comment by kvch** [comment] 2021-05-18 12:04
I am sorry, I meant to reference the comment: https://github.com/elastic/beats/issues/25709#issuecomment-841346153
The problem was in Fleet server and was resolved by https://github.com/elastic/beats/pull/25664

When I tested the scenario above I had no problems, so I assume the PR indeed fixed the issue.

I do not know what is the state of #25709 exactly at the moment. I spent a few hours with @EricDavisX  and @michalpristas on Friday to track down the issue together.

**Comment by michalpristas** [comment] 2021-05-18 12:06
to describe a problem: 
the problem was that after restart we had output configuration broken and pointing to localhost even though it was on cloud. so after restart logs were sent to void.
after a fix, we dont overwrite output which keeps logs being sent to correct location
