### ISSUE TITLE
Aborting upgrade of a large number of agents results in instability

### ISSUE THREAD

**Issue by ablnk** [elastic/fleet-server#1617] opened 2022-06-29 14:34 UTC
**Kibana version:**
8.3.0 SNAPSHOT
Build 86bc2a3e

**Environment:**
perf-rjktl-custom

**Precondition to reproduce:**
Have **15k** agents in Fleet under the same policy.

**Steps to reproduce:**
1. Click on the select all checkbox. then "Select everything on all pages".
2. Select "Upgrade agents" in actions.
3. After upgrade operation is started, click on the "Abort upgrade" button, confirm choice.

**Actual result:**
Agents gradually go offline. Over time, everything only degraded and an even greater number of agents went offline without recovering. At 15:07 I had 6 agents went offline, at 15:44 I had 4113 agents went offline. 
I found the following error in logs:
https://monitoring-oblt.elastic.dev/app/discover#/doc/bd959b40-c7b1-11ec-bdad-d789db40ae72/.ds-elastic-cloud-logs-8-2022.06.24-000006?id=69KZr4EBczFln0Rf8Ll5
```json
{
   "_index":".ds-elastic-cloud-logs-8-2022.06.24-000006",
   "_id":"69KZr4EBczFln0Rf8Ll5",
   "_version":1,
   "_score":1,
   "_source":{
      "@timestamp":"2022-06-29T13:15:03.946Z",
      "message":"http: TLS handshake error from 10.47.192.54:37922: EOF\n",
      "log":{
         "offset":390820,
         "file":{
            "path":"/app/elastic-agent/data/logs/es-containerhost/fleet-server-20220629-37.ndjson"
         }
      },
      "log.level":"error",
      "agent":{
         "id":"9cff83a3-62b6-43b1-bb75-7e4058cc6722",
         "name":"e83562cfc533",
         "type":"filebeat",
         "version":"8.3.0",
         "ephemeral_id":"852ceef5-a399-4f0c-9a22-4cef2775fbb4"
      },
      "ecs":{
         "version":"8.0.0"
      },
      "service.name":"fleet-server",
      "ecs.version":"1.6.0",
      "input":{
         "type":"log"
      },
      "event":{
         "dataset":"agent.log"
      },
      "service":{
         "id":"ffd9882b25fc67cad1b88b2493dedba7",
         "node":{
            "name":"instance-0000000000"
         },
         "version":"8.3.0-SNAPSHOT",
         "type":"agent",
         "name":"perf-rjktl-custom"
      },
      "cloud":{
         "availability_zone":"us-west2-b"
      },
      "host":{
         "name":"e83562cfc533"
      }
   },
   "fields":{
      "service.name":[
         "perf-rjktl-custom",
         "fleet-server"
      ],
      "service.id":[
         "ffd9882b25fc67cad1b88b2493dedba7"
      ],
      "service.node.name":[
         "instance-0000000000"
      ],
      "input.type":[
         "log"
      ],
      "log.offset":[
         390820
      ],
      "message":[
         "http: TLS handshake error from 10.47.192.54:37922: EOF\n"
      ],
      "cloud.availability_zone":[
         "us-west2-b"
      ],
      "service.type":[
         "agent"
      ],
      "agent.type":[
         "filebeat"
      ],
      "@timestamp":[
         "2022-06-29T13:15:03.946Z"
      ],
      "agent.id":[
         "9cff83a3-62b6-43b1-bb75-7e4058cc6722"
      ],
      "service.version":[
         "8.3.0-SNAPSHOT"
      ],
      "ecs.version":[
         "8.0.0",
         "1.6.0"
      ],
      "log.file.path":[
         "/app/elastic-agent/data/logs/es-containerhost/fleet-server-20220629-37.ndjson"
      ],
      "log.level":[
         "error"
      ],
      "agent.ephemeral_id":[
         "852ceef5-a399-4f0c-9a22-4cef2775fbb4"
      ],
      "agent.version":[
         "8.3.0"
      ],
      "agent.name":[
         "e83562cfc533"
      ],
      "host.name":[
         "e83562cfc533"
      ],
      "event.dataset":[
         "agent.log"
      ]
   }
}
```

Here is some metrics:
![integrations server](https://user-images.githubusercontent.com/34958359/176462868-91be7a57-e4e2-4945-9eaa-77925644fd08.jpg)
![elasticsearch metrics](https://user-images.githubusercontent.com/34958359/176462914-cc8571fe-af68-4f76-b387-3737f8abb7cd.jpg)
![elasticsearch node1](https://user-images.githubusercontent.com/34958359/176462919-8abd3775-4267-4732-8cca-9b4b8114f2bf.jpg)
![elasticsearch node2](https://user-images.githubusercontent.com/34958359/176462923-3b2c1ca9-5b78-4d4f-9ead-b814faa35411.jpg)
![elasticsearch node3](https://user-images.githubusercontent.com/34958359/176462931-8ad42f3d-883f-4d63-8de3-7dc556803c74.jpg)

**Expected result:**
Upgrade is cancelled for all agents, initial agent version is displayed next to every agent. All selected agents are "Healthy"

**Comment by ablnk** [comment] 2022-06-29 14:36
@jlind23 @joshdover @nimarezainia

**Comment by ph** [comment] 2022-06-29 15:54
@AndersonQ Please verify in fleet-server is there is any panic, we have merge this https://github.com/elastic/fleet-server/pull/1597 not sure if this was included in the current tested artifact.

**Comment by ph** [comment] 2022-06-29 17:06
@nchaulet Can you give me the step of what is happening when an abort is done on Fleet?

**Comment by joshdover** [comment] 2022-06-30 11:57
> * Since the actions weren't cancelled, the drones were receiving errors when trying to ack the upgrade action that had already been cancelled. It's possible the drone got into some error loop. I'll try to reproduce this.

This doesn't seem to check out. The drones will still do the upgrade, but they don't seem to get stuck in a bad state of any kind. Something must be happening at scale here.

Still, the cancel behavior does need to be fixed in horde.

**Comment by joshdover** [comment] 2022-07-19 10:13
@ablnk @pjbertels Have we seen this happen again? If not I think we can close this and re-open with more evidence if we have it.

> * It's possible that too many upgrades were being downloaded at once (too small of an upgrade window was chosen) causing general network congestion problems in the k8s cluster. This could explain the TLS handshake errors that were being seen

I think using the new `upgrade_mode=check_exists` option should help if this were the cause. Could we test with this and close this issue if we can't reproduce anymore?

**Closed** 2022-07-19 12:45 UTC
Labels: Team:Elastic-Agent-Control-Plane
