### ISSUE TITLE
Gracefully handle many subsequent policy changes

### ISSUE THREAD

**Issue by joshdover** [elastic/fleet-server#2492] opened 2023-04-12 13:37 UTC
We are seeing in our scale tests that when we test applying 10 changes to a policy in quick succession, we create a lot of load on the system as each agent goes through the checkin-ack-checkin flow for each policy change.

While this scenario is not likely when a user uses the UI to make changes to policies, it will be a situation users encounter when using automation against the Fleet API (which we want to make GA soon).

To prevent this problem, we should add a debounce to the policy monitor so that many subsequent policy changes that happen in a small window are not all applied and instead only the last policy update is delivered to connected agents.

I'd recommend a 1 second debounce to start, but make this a configurable setting the user can change from the Fleet Server policy. Note this will introduce a delay from saving a change in the UI and having it pushed out to agents.

**Comment by pjbertels** [comment] 2023-04-13 12:33
>not likely when a user uses the UI to make changes to policies, it will be a situation users encounter when using automation against the Fleet API 

IMO this scenario is equally likely when using Kibana or the Fleet API. I don't think that Kibana prevents you from making a bunch of policy changes in quick succession. The test actually was created by Andrei as a manual test first. While I don't think it is a good idea and I don't do it personally ... my experience with many customers is ... if you don't prevent it then some users will click through the GUI as fast as they can.

**Comment by juliaElastic** [comment] 2024-01-23 16:23
Closing this as a duplicate of https://github.com/elastic/ingest-dev/issues/2777

**Closed by juliaElastic** 2024-01-23 16:23 UTC
Labels: enhancement, Team:Fleet, Project:FleetScaling
