### ISSUE TITLE
Fleet-Server - reduce noise from Elasticsearch deprecation logs

### ISSUE THREAD

**Issue by jlind23** [elastic/fleet-server#979] opened 2021-12-08 15:26 UTC

**Comment by cmacknz** [comment] 2021-12-22 19:40
Closing this one. I set up fleet using `elastic-package stack up --version 8.0.0-SNAPSHOT`, installed the osquery manager integration, ran some queries and investigated the elasticsearch logs. 

There were several deprecation warnings found, but none that appear to be caused by the elastic agent or fleet. I'm following up on the warnings I did find separately.

**Closed by cmacknz** 2021-12-22 19:40 UTC
Labels: v8.0.0, Team:Elastic-Agent-Control-Plane
