### ISSUE TITLE
duplicate fleet server entries

### ISSUE THREAD

**Issue by pjbertels** [elastic/fleet-server#2489] opened 2023-04-11 15:50 UTC
Fleet often shows duplicate agent entries under error conditions. Duplicate agent entries has implications beyond the same laptop showing up twice in Fleet(which we should not allow to happen) when we get in a crash loop things like this happen ... the same 4 fleet servers repeated many times showing as stuck in updating.

![image](https://user-images.githubusercontent.com/4389260/231215504-50efdbbc-5524-4d8e-b768-2825dcce3824.png)

It is obvious based on the host name reported for these agents that the intent of the hostname is to ensure the agents are unique but Fleet can't figure it out.

![image](https://user-images.githubusercontent.com/4389260/231215887-d2df46c8-3d18-4ac4-aad6-e356d3c0e5bb.png)

IMO we need to be better here. If we can't figure out if the same agent is contacting us over and over then we should support a setting in Fleet where the user can specify the hostnames are unique so customers who have unique hostnames can avoid these problems.

These are from 8.8-SNAPSHOT.

**Comment by jlind23** [comment] 2023-04-11 16:33
@kpollich @juliaElastic have tou already seen anything like this?

**Comment by juliaElastic** [comment] 2023-04-12 06:51
Yes, when the agent crashes with an error, and restarts, the new agent shows up as a new entry in the agents list. Can this behaviour be changed on the Agent side? @michel-laterman @cmacknz

**Comment by jlind23** [comment] 2023-04-12 08:21
adding @pierrehilbert as we might need to sneak it into one of our upcoming sprint

**Comment by cmacknz** [comment] 2023-04-19 00:28
Is the agent running in Elastic Cloud or K8S here? 

Part of the problem is we rely on the agent ID to uniquely identify fleet server, but when the agent runs in a container the filesystem is discarded on each restart so you can't persist it unless you have a way to store the state on a  separate persistent volume.

In K8S you can probably solve this by configuring the state path to use a host path volume mounted from the node running the agent as described in https://github.com/elastic/elastic-agent/issues/2109.

In Elastic Cloud we'll need to ask the cloud team for suggestions on how to configure this for Integrations Server (if we do this here we need to convert it to a private issue first). I'm not sure if we are constrained to ephemeral file systems with Integrations Server today.

Trying to uniquely identify agents based on something other than the agent ID could work and that is a Fleet specific problem. This wouldn't solve the problem in general though, as the hostname isn't guaranteed to be unique per agent instance. In k8s the hostname may include the pod name which is regenerated frequently.

**Comment by pjbertels** [comment] 2023-04-21 15:27
These tests are in Elastic Cloud.
I have another example of this problem. In this case these are Horde drones. Here is an example where we are starting up 500 drones, we get 500 running and then one of them gets counted twice(in the 'updating' state). 
![image](https://user-images.githubusercontent.com/4389260/233675078-c3a07d9b-5935-4206-8a27-0607c6890d4c.png)

**Comment by jlind23** [comment] 2024-05-28 13:12
This hadn't come up in a while hence closing as outdated, feel free to reopen it if needed.

**Closed by jlind23** 2024-05-28 13:12 UTC
Labels: Team:Elastic-Agent, Team:Fleet
